# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7e0169141d4ff83e77cce255e30bd08dac98dac0d7f87dbecce6a131e27470aa33a5e096f170c07a20dd69640145082e654cda02686bf451782ff2025c12a5b

test:
  secret_key_base: 8fa9c36179db18f5516f5320b12ef105116eceff22c1dd334a2739a758dfb5f833a7668cd560c9a27e84b0ea2c012f0d5b22507920f278674dc3a8ca0aa575ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
